name: Build and deploy staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Setup
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v3.1.0
        with:
          REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
          TARGET: ${{ secrets.SSH_STAGING_TARGET }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_STAGING_PRIVATEKEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.SSH_STAGING_HOST }}
          REMOTE_USER: ${{ secrets.SSH_STAGING_USER }}
          REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
          TARGET: ${{ secrets.SSH_STAGING_TARGET }}
